name: Test Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
工作流_调度:

工作:
建设:
连续运行: Ubuntu-最新版
步伐:
      - 使用: 动作/签出@v3
随着:
提取深度: 0
      - 名字: 与格拉德勒一起构建
奔跑: |
chmod +x gradlew
。/grad Lew汇编程序ease-build-cache-parallel-daemon-warning-mode all
      - 名字: 准备应用程序
奔跑: |
mkdir-p $ { { github . workspace } }/apk/
对于“查找~-名称”中的文件。apk “——打印`；做
mv " $ file " $ { { github . workspace } }/apk/
完成的
      - 名字: 将应用程序上传到工件
使用: 动作/上传-工件@v3
随着:
名字: com.github.tvbox.osc
小路: ${{github.workspace}}/apk/*
